#ifndef MK1MF_BUILD
    /* auto-generated by util/mkbuildinf.pl for crypto/cversion.c */
    #define CFLAGS cflags
    /*
     * Generate CFLAGS as an array of individual characters. This is a
     * workaround for the situation where CFLAGS gets too long for a C90 string
     * literal
     */
    static const char cflags[] = {
        'c','o','m','p','i','l','e','r',':',' ','a','a','r','c','h','6','4','-',
        'l','i','n','u','x','-','a','n','d','r','o','i','d','-','g','c','c',' ',
        '-','I','.',' ','-','I','.','.',' ','-','I','.','.','/','i','n','c','l',
        'u','d','e',' ',' ','-','f','P','I','C',' ','-','D','O','P','E','N','S',
        'S','L','_','P','I','C',' ','-','D','D','S','O','_','D','L','F','C','N',
        ' ','-','D','H','A','V','E','_','D','L','F','C','N','_','H',' ','-','D',
        'B','_','E','N','D','I','A','N',' ','-','D','S','H','A','R','E','D','_',
        'E','X','T','E','N','S','I','O','N','=','.','s','o',' ','-','f','P','I',
        'C',' ','-','D','O','P','E','N','S','S','L','_','P','I','C',' ','-','D',
        'D','S','O','_','D','L','F','C','N',' ','-','D','H','A','V','E','_','D',
        'L','F','C','N','_','H',' ','-','m','a','n','d','r','o','i','d',' ','-',
        'I','/','h','o','m','e','/','v','i','n','t','o','n','/','a','n','d','r',
        'o','i','d','-','n','d','k','-','r','1','3','b','/','p','l','a','t','f',
        'o','r','m','s','/','a','n','d','r','o','i','d','-','2','1','/','a','r',
        'c','h','-','a','r','m','6','4','/','u','s','r','/','i','n','c','l','u',
        'd','e',' ','-','B','/','h','o','m','e','/','v','i','n','t','o','n','/',
        'a','n','d','r','o','i','d','-','n','d','k','-','r','1','3','b','/','p',
        'l','a','t','f','o','r','m','s','/','a','n','d','r','o','i','d','-','2',
        '1','/','a','r','c','h','-','a','r','m','6','4','/','u','s','r','/','/',
        'l','i','b',' ','-','O','3',' ','-','f','o','m','i','t','-','f','r','a',
        'm','e','-','p','o','i','n','t','e','r',' ','-','W','a','l','l',' ','-',
        'O','3',' ','-','W','a','l','l','\0'
    };
    #define PLATFORM "platform: linux-generic64"
    #define DATE "built on: Sat Aug 11 15:50:55 2018"
#endif
